@startuml
activate CategoryUI
CategoryUI -> CategoryController : createCategory(boolean isAProduct)
deactivate CategoryUI
activate CategoryController
CategoryController -> CategoryFacade : updateCategory(idProduct: int, quantity: int)
activate CategoryFacade
CategoryFacade -> DAOFactoryMySQL : createCategoryDAO()
activate DAOFactoryMySQL
DAOFactoryMySQL --> CategoryDAOMySQL: new()
activate CategoryDAOMySQL
CategoryDAOMySQL --> CategoryFacade: CategoryDAO
CategoryFacade -> CategoryDAOMySQL : updateCategory(in Category:Category)
CategoryDAOMySQL -> MySQLConnection : createStatement()
activate MySQLConnection
MySQLConnection --> CategoryDAOMySQL: true
activate Category
CategoryDAOMySQL -> Category : new()
Category --> CategoryDAOMySQL : Category
deactivate Category
CategoryDAOMySQL --> CategoryFacade : Category
deactivate DAOFactoryMySQL
deactivate CategoryFacade
deactivate CategoryDAOMySQL
deactivate MySQLConnection
CategoryFacade --> CategoryController
CategoryController -> CategoryController : getInstance.display("New category")
deactivate CategoryController
deactivate Category
deactivate CategoryFacade
@enduml