@startuml
autonumber
activate LoginUI
LoginUI -> LoginController : login()
deactivate LoginUI
activate LoginController
LoginController -> UserFaçade : login ( pseudo:String, password : String)

activate UserFaçade
UserFaçade --> DAOFactoryMySQL : new()
activate DAOFactoryMySQL
DAOFactoryMySQL --> UserFaçade : AbstractFactoryDAO
UserFaçade ->DAOFactoryMySQL : createUserDAO()
activate UserDAOMySQL
DAOFactoryMySQL --> UserDAOMySQL : new()
UserDAOMySQL -->UserFaçade : UserDA0
UserFaçade -> UserDAOMySQL : login(pseudo:String, password:String)
activate MySQLConnection
UserDAOMySQL -> MySQLConnection : createStatement()
MySQLConnection --> UserDAOMySQL : true
deactivate MySQLConnection
activate User
UserDAOMySQL --> User : new()
User --> UserDAOMySQL : User

deactivate User


UserDAOMySQL --> UserFaçade : User

deactivate UserDAOMySQL
deactivate DAOFactoryMySQL
UserFaçade->UserFaçade : getInstance().setConnected(User: User)

UserFaçade --> LoginController
LoginController --> UserFaçade : isConnected()

alt successful case
    UserFaçade -> LoginController : true
    LoginController -> router.Router : getInstance().activate("HomePage")


else
    UserFaçade -> LoginController : false
    LoginController -> LoginController : display("Wrong combination of password and pseudo")


end
deactivate UserFaçade
deactivate LoginController

@enduml